// <auto-generated />
using MechanicShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MechanicShop.Migrations
{
    [DbContext(typeof(MechanicShopContext))]
    [Migration("20210215230615_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MechanicShop.Models.management", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("management_Contract")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("management_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("management_Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("management_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("management_Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("management");
                });
#pragma warning restore 612, 618
        }
    }
}
